services:
  - type: web
    name: smart-email-writer-sb
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/email-writer-sb-0.0.1-SNAPSHOT.jar
    envVars:
      - key: GEMINI_KEY
        sync: false
      - key: PORT
        value: 8080
      - key: APP_ENV
        value: production
